### ISSUE TITLE
Ui.png missing in project showcase page

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103-T11-3/main#118]
See https://nus-cs2103-ay1920s1.github.io/website/admin/projectList.html#cs2103-t11-3

**Comment by ooimingsheng** [comment]
Hi Prof, 

I thought the problem might be that we our file in our docs/images was named Ui.PNG so i changed it to Ui.png but i was unable the website does not seem to reflect this. Is this the correct approach or am i supposed to upload somewhere else?

**Comment by ooimingsheng** [comment]
hi Prof, 

We have rectified it. If there are any other issues please let us know.

**Comment by damithc** [comment]
Seems to be fixed now @ooimingsheng  👍
